// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qinxiaogit/k8sToGo/mic/api/protobuf/auth/v1"
	"github.com/qinxiaogit/k8sToGo/mic/internal/auth"
	"github.com/qinxiaogit/k8sToGo/mic/internal/pkg/config"
	"github.com/qinxiaogit/k8sToGo/mic/internal/pkg/jwt"
	"github.com/qinxiaogit/k8sToGo/mic/internal/pkg/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// 初始化服务
func InitServer(logger *log.Logger, conf *config.Config) (v1.AuthServiceServer, error) {
	manage := jwt.NewManage(logger, conf)
	authServiceServer := auth.NewServer(logger, manage)
	return authServiceServer, nil
}
