// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qinxiaogit/k8sToGo/mic/api/protobuf/user/v1"
	"github.com/qinxiaogit/k8sToGo/mic/internal/pkg/config"
	"github.com/qinxiaogit/k8sToGo/mic/internal/pkg/dbcontext"
	"github.com/qinxiaogit/k8sToGo/mic/internal/pkg/log"
	"github.com/qinxiaogit/k8sToGo/mic/internal/user"
)

// Injectors from wire.go:

func InitServer(logger *log.Logger, conf *config.Config) (v1.UserServiceServer, error) {
	db, err := dbcontext.NewUserDB(conf)
	if err != nil {
		return nil, err
	}
	repository := user.NewRepository(logger, db)
	userServiceServer := user.NewServer(logger, repository)
	return userServiceServer, nil
}
